python: 3.6

sudo: required

services:
  - docker

language: python

script:
  - python -m pytest -v

after_success:
  - sh .travis/deploy_dockerhub.sh
  - test “cicd-buzz” = “master” && sh .travis/deploy_heroku.sh